### ISSUE TITLE
[wiki-tutorial] Restore of `vdso` fails

### ISSUE THREAD

**Issue by blackgeorge-boom** [ssrg-vt/TransProc#17]
Hello, thank you for the cool software!

I'm trying to run the simple migration example in the wiki: https://github.com/ssrg-vt/TransProc/wiki/Migrate-a-Simple-Program

I'm using the (recommended) emulated environment: https://github.com/ssrg-vt/TransProc/wiki/Emulated-Environment-Setup

For some reason, the restore step fails on aarch64, stumbling on a `vdso` issue:

```
...
task_args->pid: 5707
task_args->nr_threads: 1
task_args->clone_restore_fn: 0x117d8
task_args->thread_args: 0x23500
(00.200134) pie: 5707: Switched to the restorer 5707
(00.202826) pie: 5707: vdso: Remap rt-vdso 0xffffbed03000 -> 0x29000
(00.204472) pie: 5707: vdso: Remap rt-vvar 0xffffbed02000 -> 0x28000
(00.205349) pie: 5707: vdso: Using gettimeofday() on vdso at 0x29498
(00.216395) pie: 5707: vdso: Using gettimeofday() on vdso at 0x29498
(00.217201) pie: 5707:  mmap(0x4ff000 -> 0x500000, 0x3 0x12 3)
(00.218696) pie: 5707:  mmap(0x500000 -> 0x508000, 0x7 0x12 3)
(00.219331) pie: 5707:  mmap(0x600000 -> 0x602000, 0x1 0x12 3)
(00.219913) pie: 5707:  mmap(0x700000 -> 0x702000, 0x3 0x12 3)
(00.220553) pie: 5707:  mmap(0x800000 -> 0x802000, 0x3 0x32 -1)
(00.221626) pie: 5707:  mmap(0x803000 -> 0x804000, 0x1 0x12 3)
(00.222916) pie: 5707:  mmap(0x900000 -> 0x901000, 0x1 0x12 3)
(00.223950) pie: 5707:  mmap(0xa00000 -> 0xa02000, 0x1 0x12 3)
(00.225060) pie: 5707:  mmap(0x7ffcf91a1000 -> 0x7ffcf91c2000, 0x3 0x132 -1)
(00.226071) pie: 5707:  mmap(0xffffacaa5000 -> 0xffffacaa6000, 0x3 0x32 -1)
(00.227615) pie: 5707:  mmap(0xffffacaa6000 -> 0xffffacaa7000, 0x7 0x32 -1)
(00.228614) pie: 5707: Preadv 0x500000:8192... (6 iovs)
(00.233700) pie: 5707: `- returned 45056
(00.234791) pie: 5707:    `- skip pagemap
(00.235264) pie: 5707:    `- skip pagemap
(00.235658) pie: 5707:    `- skip pagemap
(00.236045) pie: 5707:    `- skip pagemap
(00.236427) pie: 5707:    `- skip pagemap
(00.236808) pie: 5707:    `- skip pagemap
(00.237806) pie: 5707: vdso: Parsing at 0xffffacaa6000 0xffffacaa7000
(00.239048) pie: 5707: vdso: PT_LOAD p_vaddr: 0x0
(00.239743) pie: 5707: vdso: DT_HASH: 0x120
(00.240178) pie: 5707: vdso: DT_STRTAB: 0x1e0
(00.240663) pie: 5707: vdso: DT_SYMTAB: 0x150
(00.241072) pie: 5707: vdso: DT_STRSZ: 0x77
(00.241563) pie: 5707: vdso: DT_SYMENT: 0x18
(00.242585) pie: 5707: vdso: nbucket 0x3 nchain 0x6 bucket 0xffffacaa6128 chain 0xffffacaa6134
(00.243685) pie: 5707: vdso: image [vdso] 0xffffacaa6000-0xffffacaa7000 [vvar] 0xffffacaa5000-0xffffacaa6000
(09.180370) Error (criu/cr-restore.c:1562): 5707 killed by signal 11: Segmentation fault
(09.184215) Error (criu/cr-restore.c:2483): Restoring FAILED.
```

Do you know what the issue might be? I have tried running the `vdso/vdso.sh` script to initialize the vdso templates (although this step is not needed for the emulated environments provided), but it didn't work.

Not sure if this repo is still maintained, but I appreciate your time in any case.

**Comment by blackgeorge-boom** [comment]
Ok, it seems that even though the kernel versions were the same major revision between the architectures:

```bash
5.4.0-193-generic aarch64
```
vs
```bash
5.4.0-196-generic x86_64
```

I still had to apply the [steps](https://github.com/ssrg-vt/TransProc/wiki/Updating-vDSO-Template-in-the-Repository) to update the vdso templates on both hosts. And, also, transfer the updated templates between the hosts.

Now, it works.

**Comment by xjtuwxg** [comment]
> Ok, it seems that even though the kernel versions were the same major revision between the architectures:
> 
> ```shell
> 5.4.0-193-generic aarch64
> ```
> 
> vs
> 
> ```shell
> 5.4.0-196-generic x86_64
> ```
> 
> I still had to apply the [steps](https://github.com/ssrg-vt/TransProc/wiki/Updating-vDSO-Template-in-the-Repository) to update the vdso templates on both hosts. And, also, transfer the updated templates between the hosts.
> 
> Now, it works.

Yes, you will need to update the vdso templates. Sorry for seeing this issue late.

**Comment by blackgeorge-boom** [comment]
> > Ok, it seems that even though the kernel versions were the same major revision between the architectures:
> > ```shell
> > 5.4.0-193-generic aarch64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > vs
> > ```shell
> > 5.4.0-196-generic x86_64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I still had to apply the [steps](https://github.com/ssrg-vt/TransProc/wiki/Updating-vDSO-Template-in-the-Repository) to update the vdso templates on both hosts. And, also, transfer the updated templates between the hosts.
> > Now, it works.
> 
> Yes, you will need to update the vdso templates. Sorry for seeing this issue late.

No problem, thanks a lot for your reply!
